<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.Azure.CosmosDB" Version="13.3.5" />
      <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.8" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SharedTypes\SharedTypes.csproj" />
    </ItemGroup>

</Project>
