<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Azure.Cosmos.Client">
      <HintPath>..\..\..\..\..\..\.nuget\packages\microsoft.azure.cosmos\3.54.0\lib\netstandard2.0\Microsoft.Azure.Cosmos.Client.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\DetectionDatabase\DetectionDatabase.csproj" />
  </ItemGroup>

</Project>
