<Project Sdk="Aspire.AppHost.Sdk/13.0.0">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>2ce16ec9-aa23-49fa-b61f-74dc4aa5f643</UserSecretsId>
    </PropertyGroup>

</Project>
